# Site settings
remote_theme: mmistakes/minimal-mistakes

title: Roozbeh Atri
description: >-
  AI/ML Engineer | Reinforcement Learning | Healthcare AI
url: "https://roozbehatri.github.io" # Change 'yourusername' to your GitHub username
baseurl: ""

author:
  name: Roozbeh Atri, PhD
  avatar: /assets/images/avatar.png # You can upload your avatar image to this path
  bio: AI/ML Engineer specializing in Reinforcement Learning and Healthcare AI. Focused on real-time systems and patient-centered solutions.
  location: New York, NY
  email: roozbeh.atri@gmail.com
  linkedin: roozbeh-atri
  github: roozbehatri

# Appearance settings
minimal_mistakes_skin: default

# Social links
social:
  type: Person
  name: Roozbeh Atri
  links:
    - "https://www.linkedin.com/in/roozbeh-atri/"
    - "https://github.com/roozbehatri"
    - "mailto:roozbeh.atri@gmail.com"

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/

# Plugins (GitHub Pages-supported)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Optional analytics (comment out if not using)
# google_analytics: UA-XXXXXXXXX-X