# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

# Site Settings
locale: "en-US"
title: "Roozbeh Atri, PhD"
title_separator: "-"
name: "Roozbeh Atri"
description: "Experienced AI/ML engineer passionate about creating scalable, data-centric solutions across diverse domains."
url: "https://roozbehatri.github.io"
baseurl: ""
repository: "roozbehatri/roozbehatri.github.io"

# Author Details
author:
  name: "Roozbeh Atri"
  avatar: "/assets/images/avatar.png"  # Personal photo
  logo: "/assets/images/roozbeh_logo.png"  # Site logo
  favicon: "/assets/images/favicon.png"  # Recommended: separate favicon file, 32x32 px
  bio: "Experienced AI/ML engineer passionate about creating scalable, data-centric solutions across diverse domains."
  location: "New York, NY"
  # email: "roozbeh.atri@gmail.com"
  masthead_title: "Roozbeh Atri"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:roozbeh.atri@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/roozbeh-atri/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/roozbehatri"

# Social Sharing
social:
  type: "Person"
  name: "Roozbeh Atri"
  links:
    - "https://www.linkedin.com/in/roozbeh-atri/"
    - "https://github.com/roozbehatri"
    - "mailto:roozbeh.atri@gmail.com"

# Open Graph image for social sharing (optional but recommended)
og_image: "/assets/images/roozbeh_logo.png"

# Navigation Menu
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/

# Plugins (GitHub Pages-supported)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/roozbeh-atri"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/roozbehatri"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:roozbeh.atri@gmail.com"

# Search (optional but useful)
search: true
search_full_content: true

# Google Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XXXXXXXXXX"  # Replace with your actual Google Analytics ID (must start with "G-")

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone:

# Pagination
paginate: 5
paginate_path: /page:num/

pagination:
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments:
      share: true
      related: true